image: docker:latest
services:
  - docker:dind

stages:
  - build
  - stylecheck
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-accelerated:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE --file Dockerfile .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - master
    - tags
  tags:
    - docker

build-py35:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE-py35 --file Dockerfile.py35 .
    - docker push $CONTAINER_TEST_IMAGE-py35
  tags:
    - docker

# pep8 runs different tests for different Python versions
test-py35-pep8:
  stage: stylecheck
  script:
    - docker pull $CONTAINER_TEST_IMAGE-py35
    - docker run $CONTAINER_TEST_IMAGE-py35 tox -e pep8
  tags:
    - docker

test-py35-docs:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE-py35
    - docker run $CONTAINER_TEST_IMAGE-py35 tox -e docs
  tags:
    - docker

test-py35-tests:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE-py35
    - docker run $CONTAINER_TEST_IMAGE-py35 tox -e py35 tests
  tags:
    - docker

test-py35-integration-tests:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE-py35
    - docker run $CONTAINER_TEST_IMAGE-py35 tox -e py35 integration-tests
  tags:
    - docker
