build-test-deploy:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build -t concrete-python .
    - docker run --rm concrete-python tox -c concrete-python -e pep8,py27,py35,docs tests # configured in tox.ini
    - docker run --rm concrete-python tox -c concrete-python -e py27,py35 integration-tests
  tags:
    - docker

mac-python-test:
  before_script:
    - python --version
    - tox --version
  script:
    - tox -e pep8,py27,py35,docs tests
    - tox -e py27,py35 integration-tests
  tags:
    - mac-shell-no-docker
