language: generic

sudo: required

matrix:
    include:
        - os: linux
        - os: osx
          env:
          - LDFLAGS=-L/usr/local/opt/openssl/lib
            CPPFLAGS=-I/usr/local/opt/openssl/include


install:
    - ./.travis/install.bash

script:
  - tox -e pep8,py35,docs tests # configured in tox.ini
  - tox -e py35 integration-tests
