sudo: required

services:
  - docker

before_script:
  - docker info

script:
  - docker build -t concrete-python .
  - docker run --rm concrete-python tox # configured in tox.ini
  - docker run --rm concrete-python tox integration-tests
