sudo: required

services:
  - docker

before_script:
  - docker info

script:
  - docker build -t concrete-python .
  - docker run --rm concrete-python tox -e pep8,py27,py35,docs tests integration-tests # configured in tox.ini
